version: "2.1"

services:
  rabbitmq:
    image: rabbitmq:3.7.10-management
    ports:
      - 1883:1883
      - 5671:5671
      - 5672:5672
      - 8883:8883
      - 15671:15671
      - 15672:15672
    volumes:
      - ./rabbitmq-cfg:/etc/rabbitmq
      - ./test/_files:/etc/rabbitmq/certs
  # mosquitto:
  #   image: eclipse-mosquitto:1.5.6
  #   ports:
  #     - 1883:1883
  #     - 8883:8883
  #   volumes:
  #     - ./mosquitto-cfg/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #     - ./test/_files:/mosquitto/config/certs
  app:
    # Custom image based on clojure:openjdk-8-slim-buster. It only has
    # a couple of additional tweaks to run the entry point command
    # inside the container with the uid and gid of the owner of the
    # '/app' mount point (to avoid permission issues).
    image: 223330293187.dkr.ecr.eu-west-1.amazonaws.com/magnetcoop/lein:13f8f83
    environment:
      - MQTT_TESTS_HOST
      - MQTT_TESTS_PORT
      - MQTT_TESTS_USERNAME
      - MQTT_TESTS_PASSWORD
      - MQTT_TESTS_SSL_PORT
      - MQTT_TESTS_SSL_TLS_VERSION
      - MQTT_TESTS_SSL_CA_CRT_FILE
      - MQTT_TESTS_SSL_CRT_FILE
      - MQTT_TESTS_SSL_KEY_FILE
      - MQTT_TESTS_SSL_KEY_PASSWORD
      - AMQP_TESTS_HOST
      - AMQP_TESTS_PORT
      - AMQP_TESTS_VHOST
      - AMQP_TESTS_EXCHANGE
      - AMQP_TESTS_USERNAME
      - AMQP_TESTS_PASSWORD
      - AMQP_TESTS_SSL_PORT
      - AMQP_TESTS_SSL_TLS_VERSION
      - AMQP_TESTS_SSL_CA_CRT_FILE
      - AMQP_TESTS_SSL_CRT_FILE
      - AMQP_TESTS_SSL_KEY_FILE
      - AMQP_TESTS_SSL_KEY_PASSWORD
    command: ["lein", "repl", ":headless"]
    ports:
      - 4001:4001
    volumes:
      - .:/app:delegated
      - ~/.m2:/root/.m2:delegated
      - ~/.m2:/home/magnet/.m2:delegated
    depends_on:
      - rabbitmq
